server:
  port: ${PORT:8080}


spring:
  application:
    name: info-cadastro

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  web:
    locale: pt_BR

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,metrics,logfile
        exclude:
